export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_RESPONSE = 'LOAD_QUESTIONS_RESPONSE';
export const LOAD_QUESTIONS_FAILED = 'LOAD_QUESTIONS_FAILED';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SUBMIT_QUESTION = 'SUBMIT_QUESTION';
