export const ADD_ANSWER = 'ADD_ANSWER';
export const ADD_QUESTION_USER = 'ADD_QUESTION_USER';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_RESPONSE = 'LOAD_USERS_RESPONSE';
export const LOAD_USERS_FAILED = 'LOAD_USERS_FAILED';
